# Configuration de la base de données
spring.datasource.url=jdbc:postgresql://localhost:5432/tsinjo
spring.datasource.username=fetra
spring.datasource.password=Irving11
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration HikariCP
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5

# Autoriser l'override des beans si nécessaire
spring.main.allow-bean-definition-overriding=true
spring.flyway.url=${spring.datasource.url}
spring.flyway.user=${spring.datasource.username}
spring.flyway.password=${spring.datasource.password}
spring.flyway.locations=classpath:db/migration